config/routes.rb
Rails.application.routes.draw do
  root to:'static_pages#home'
  get '/contact', to:'static_pages#contact', as: 'contact'
  get '/about', to:'static_pages#about', as: 'about'
  get '/about/toi', to:'static_pages#toi', as: 'toi'
  get '/about/ton_groupe', to:'static_pages#ton_groupe', as: 'ton_groupe'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def toi
  end

  def ton_groupe
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JeMePresente</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>
<a href='<%= toi_path %>'><p>Toi</p></a>
<a href='<%= ton_groupe_path %>'><p>Ton groupe</p></a>
<p><a href='/'>Retour à l'accueil</a></p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>Nicolas , @nicolas</p>

<p><a href='/'>Retour à l'accueil</a></p>

app/views/static_pages/home.html.erb
<h1>Home page</h1>
<p><a href='<%= about_path %>'>about</a></p>
<p><a href='<%= contact_path %>'>contact</a></p>

app/views/static_pages/toi.html.erb
Moi c'est Nico

<a href='<%= about_path %>'><br>retour</a>

app/views/static_pages/ton_groupe.html.erb
Mon groupe c'est les BGs de Grenoble

<a href='<%= about_path %>'><br>retour</a>